---

- name: add elasticsearch 1.3 to sources
  tags: elasticsearch
  apt_repository:
    repo: 'deb http://packages.elasticsearch.org/elasticsearch/1.3/debian stable main'
    state: present
    update_cache: yes

- name: install elasticsearch
  tags: elasticsearch
  apt: state=latest force=yes pkg={{item}}
  with_items:
    - elasticsearch

- name: install the elasticsearch service
  service: name=elasticsearch enabled=yes state=started

- name: copy the custom elasticSearch configuration
  template: src=elasticsearch.yml dest={{ elasticsearch.config }}