---

- name: Copy the ubuntu .ssh
  sudo_user: ubuntu
  copy: src={{ item }} dest=~/.ssh/ mode=0644
  with_fileglob:
    - .ssh/ubuntu/*

- name: Copy the root .ssh
  copy: src={{ item }} dest=~/.ssh/ mode=0644
  with_fileglob:
    - .ssh/root/*

- name: Set right permission for id_rsa
  command: chmod 0700 {{ item }}
  with_items:
    - ~/.ssh/id_rsa
    - /home/ubuntu/.ssh/id_rsa

- name: Set right permission for id_rsa.pub
  command: chmod 0644 {{ item }}
  with_items:
    - ~/.ssh/id_rsa.pub
    - /home/ubuntu/.ssh/id_rsa.pub
