---

- name: Add LXC repository
  apt_repository:
    repo: 'ppa:ubuntu-lxc/daily'
    state: present
    update_cache: yes

- name: Install lxc packages
  apt: name={{ item }} state=latest force=yes
  tags: lxc
  with_items:
    - lxc
    - bridge-utils
    - debootstrap
    - git
    - git-core
    - dnsmasq
    - dnsmasq-utils
  ignore_errors: yes