---

- name: copy lxc-ubuntu-cloud-cronycle template
  copy: src=lxc-ubuntu-cloud-rails dest=/usr/share/lxc/templates/lxc-ubuntu-cloud-rails owner=root group=root mode=0755

- name: Add lxc ubuntu-cloud template
  shell: lxc-create --template ubuntu-cloud --name ubuntu

- name: copy ubuntu template's configuration
  copy: src=ubuntu.config dest=/tmp/ubuntu.config owner=root group=root mode=0755

- name: add ubuntu template's configuration
  shell: cat /tmp/ubuntu.config >> /var/lib/lxc/ubuntu/config

# - name: Start the container
#   shell: lxc-start --name ubuntu

# - name: Install some needed packages on the ubuntu template
#   shell: lxc-attach --name ubuntu apt-get install {{ item }} -y
#   with_items:
#     - ansible
#     - git
#   ignore_errors: yes
