---

- name: Install lxc packages
  apt: name={{ item }} state=present force=yes
  tags: lxc
  with_items:
    - lxc
    - bridge-utils
    - debootstrap
    - git
    - git-core
    - dnsmasq
    - dnsmasq-utils
