---

- name: copy ansible hosts file
  copy: src=ansible-hosts dest=/etc/ansible/hosts

- name: create ~/.ansible directory
  shell: mkdir -p ~/.ansible

- name: copy the ansible hosts file to ~/.ansible/inventory also
  copy: src=ansible-hosts dest=~/.ansible/inventory

- name: export the ANSIBLE_HOSTS env variable so it reads from ~/.ansible/inventory.
  lineinfile: dest=~/.bashrc insertafter=EOF line='export ANSIBLE_HOSTS=~/.ansible/inventory'
