#cloud-config
---

write_files:
- path: /etc/elasticsearch/elasticsearch.yml
  permissions: 0644
  owner: root:root
  content: |

    cluster:
      name: { "Ref" : "AWS::StackId" }

    path:
      work: /tmp

    plugin:
      mandatory: cloud-aws

    cloud:
      node:
        auto_attributes: true

    discovery:
      type: ec2
      zen.ping.multicast.enabled: false
      host_type: private_ip
      ec2:
        group: { "Ref" : "ElasticSearchSecurityGroup" }
        tag:
          environment: { "Ref" : "AWS::StackId" }
