---

- name: Install the git repo for lcm
  git:
    repo: git@github.com:cronycle/cronycle_lcm
    dest: /lcm
    accept_hostkey: yes

- name: Install the necessary libraries
  apt: name={{ item }} state=latest force=yes
  with_items:
    - lxc-dev
    - build-essential
    - ruby-dev

- name: copy lcm initialize script
  copy: src=initialize-lcm.sh dest=~/initialize-lcm.sh mode=775

- name: initialize lcm
  command: ~/initialize-lcm.sh
