---

- name: Install the git repo for lcm
  git:
    repo: git@github.com:cronycle/cronycle_lcm
    dest: /lcm
    accept_hostkey: yes

- name: Install the necessary libraries
  apt: name={{ item }} state=latest force=yes
  with_items:
    - lxc-dev
    - build-essential
    - ruby-dev

- name: copy lcm initialize script
  copy: src=initialize-lcm.sh dest=~/initialize-lcm.sh mode=775

- name: initialize lcm
  command: ~/initialize-lcm.sh

- name: Run local ansible-playbook to generate ssh keys
  shell: ansible-playbook playbook/prepare.yml --tags ssh-keys
  args:
    chdir: /lcm/

# - name: Run local ansible-playbook to load inventory file
#   shell: ansible-playbook playbook/prepare.yml --tags ubuntu-container
#   args:
#     chdir: /lcm/
#     creates: /lcm/.inventory

# - name: Run local ansible-playbook to prepare rails environment inside ubuntu container
#   shell: ansible-playbook playbook/build.yml
#   args:
#     chdir: /lcm/
