---

- name: Install the git repo for lcm
  git:
    repo: git@github.com:cronycle/cronycle_lcm
    dest: /lcm
    accept_hostkey: yes

- name: copy lcm initialize script
  copy: src=initialize-lcm.sh dest=~/initialize-lcm.sh mode=775

- name: initialize lcm
  command: ~/initialize-lcm.sh
