- hosts: all
  sudo: yes
  roles:
    # - common
    # - aws
    # - lxc
    #- rvm
    #- ruby
    - lcm

    #- runit
    #- docker

    # - redis
    # - nodejs
    # - hipache

    # - serf
    # - gitreceive
