- hosts: all
  gather_facts: false
  sudo: yes
  #roles:
    # - common
    # - aws
    # - lxc
    #- rvm
    #- ruby
    # - lcm
    #- lwp
  tasks:
    - name: Create log directory for redis.
      shell: mkdir -p /var/log/redis

    - name: set log directory permission
      shell: chmod 0666 /var/log/redis

    #- runit
    #- docker

    # - redis
    # - nodejs
    # - hipache

    # - serf
    # - gitreceive
