---

- name: Add lwp package key
  apt_key:
    url: http://claudyus.github.io/LXC-Web-Panel/claudyus.gpg.key
    state: present

- name: Add lwp to sources
  copy:
    dest: /etc/apt/sources.list.d/lwp.list
    content: deb http://claudyus.github.io/LXC-Web-Panel/ debian/
    owner: root
    group: root
    mode: 644

- name: Update the apt cache.
  apt: update_cache=yes

- name: Install lwp package
  apt: name=lwp state=present force=yes

- name: Create directory for lwp
  file: path=/var/lwp state=directory owner=root group=root mode=755

- name: Copy initial database schema
  command: cp /srv/lwp/lwp.db /var/lwp/lwp.db
  args:
    creates: /var/lwp/lwp.db

- name: Copy configuration
  template: src=lwp.conf.j2 dest=/etc/lwp/lwp.conf owner=root group=root mode=644
  notify: restart lwp
