---

- name: Install Hipache from our fork.
  command: npm install https://github.com/hipache/hipache/archive/0.3.1.tar.gz -g

- name: Create config directory.
  file: state=directory path=/etc/hipache/

- name: Install the configuration file.
  copy: src=hipache.json dest=/etc/hipache/hipache.json owner=root group=root mode=644

- name: Install Hipache Upstart script.
  copy: src=hipache.conf dest=/etc/init/hipache.conf owner=root group=root mode=644

- name: Install Hipache logrotate.
  copy:src=hipache.logrotate dest=/etc/logrotate/hipache owner=root group=root mode=644

- name: Enable Hipache startup.
  service: name=hipache enabled=yes

- name: Make sure it's running.
  service: name=hipache state=started
