---

- name: Clear Cache files
  shell: rm -rf /var/lib/apt/lists/partial/*

- name: Update the apt cache.
  apt: update_cache=yes

# - name: Upgrade all packages.
#   apt: upgrade=yes

- name: Install python-software-properties
  apt: pkg=python-software-properties state=installed

- name: Install ntp
  apt: pkg=ntp state=installed

- name: Enable ntp startup.
  service: name=ntp enabled=yes

- name: Make sure it's running.
  service: name=ntp state=started

- name: Install lynx
  apt: pkg=lynx-cur state=installed

- name: Fix locale.
  command: /usr/sbin/update-locale

- name: Install /etc/sudoers.tmp file.
  action: template src=../files/sudoers dest=/etc/sudoers.tmp

- name: Set the permissions.
  file: path=/etc/sudoers.tmp owner=root group=root mode=0440

- name: Final sudoers file check
  shell: visudo -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers

- name: Install new sshd config
  action: template src=../files/sshd-config dest=/etc/ssh/sshd_config

- name: Make sure permissions are correct.
  file: path=/etc/ssh/sshd_config owner=root group=root mode=0644

- name: Restart sshd.
  service: name=ssh state=restarted
