---

- name: Clear Cache files
  shell: rm -rf /var/lib/apt/lists/*

- name: Update the apt cache.
  apt: update_cache=yes

# - name: Upgrade all packages.
#   apt: upgrade=yes

- name: Install useful packages.
  apt: name={{ item }} state=installed force=yes
  with_items:
    - ansible
    - python-software-properties
    - language-pack-en
    - git
    - git-core
    - byobu
    - zsh
    - htop
    - lynx-cur
    - ntp

- name: Fix locale.
  command: /usr/sbin/update-locale

- name: Enable ntp at startup.
  service: name=ntp enabled=yes

- name: Make sure these are started
  service: name={{ item }} state=started
  with_items:
    - ntp

- name: Oh-My-Zsh
  git: accept_hostkey=true repo=git://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

- name: Install /etc/sudoers.tmp file.
  template: src=../files/sudoers dest=/etc/sudoers.tmp

- name: Set the permissions.
  file: path=/etc/sudoers.tmp owner=root group=root mode=0440

- name: Final sudoers file check
  shell: visudo -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers

- name: Install new sshd config
  template: src=../files/sshd-config dest=/etc/ssh/sshd_config

- name: Make sure permissions are correct.
  file: path=/etc/ssh/sshd_config owner=root group=root mode=0644

- name: Restart sshd.
  service: name=ssh state=restarted
